version: '3'
 
services:
    reverseproxy:
        depends_on:
            - nginx
            - apache
        image: nginx:alpine
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 8000:80
        restart: always
 
    nginx:
        image: nginx:alpine
        volumes:
          - ./app_web:/usr/share/nginx/html
        ports:
            - 8001:80
        restart: always
 
    apache:
        image: httpd:alpine
        volumes:
          - ./app_api:/usr/local/apache2/htdocs
        ports:
            - 8002:80
        restart: always